services:
  - type: web
    name: hive-mind-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: starter                   
    region: oregon                 
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false                
      - key: TAVILY_API_KEY
        sync: false
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_ENDPOINT
        value: "https://api.smith.langchain.com"
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        value: "DAG_Multi_AI_Agent_Research"
      - key: DB_URI
        sync: false
